name: "💥 Crash or Stacktrace"
description: Report any server crashes or alarming stack traces.
type: "Bug"
labels:
  - "status: needs triage"
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. You are running the latest version of Paper from [our downloads page](https://papermc.io/downloads/paper).
        2. Your version of Minecraft is supported by Paper.

        If your server crash log contains `DO NOT REPORT THIS TO PAPER`, please ask in our
        [Discord](https://discord.gg/papermc) before opening this issue. These messages are informing you of server
        lag and providing debug information.

  - type: textarea
    attributes:
      label: Stack trace
      description: |
        We need all of the stack trace! Do not cut off parts of it. Please do not use attachments.
        If you prefer, you can use a paste site like https://mclo.gs.
      value: |
        ```
        paste your stack trace or a mclo.gs link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin and Datapack List
      description: |
        All plugins and datapacks running on your server.
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actions to reproduce (if known)
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue. Anything helps!
    validations:
      required: false

  - type: textarea
    attributes:
      label: Paper version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [20:34:42 INFO]: Checking version, please wait...
        [20:34:42 INFO]: This server is running Paper version 1.21-105-master@7e91a2c (2024-07-20T21:04:31Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
        [20:34:42 INFO]: You are running the latest version
        [20:34:42 INFO]: Previous version: 1.21-103-aa3b356 (MC: 1.21)
        ```

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below, if any.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
