name: Performance Problem
description: Report performance related problems or other areas of concern
body:
  - type: markdown
    attributes:
      value: |
        Before reporting performance problems here, please make sure you are on the latest version of Paper.
        Forks of Paper receive no support here. If you are using a fork, please make sure that this problem also affects Paper.
  - type: input
    attributes:
      label: Timings or Profile link
      description: We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.
      placeholder: "Example: https://timings.aikar.co/?id=6b48586fbbdd48e585ca0ebb07c59dd0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
      description: If applicable, please describe your issue.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Server config files
      description: We need bukkit.yml, spigot.yml, paper.yml, and server.properties. You can paste it below or use a paste site like https://paste.gg.
      value: |
        ```
        Paste configs or paste.gg link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Paper version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [20:34:42 INFO]: This server is running Paper version git-Paper-540 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
        [20:34:42 INFO]: Checking version, please wait...
        [20:34:42 INFO]: Previous version: git-Paper-538 (MC: 1.16.5)
        [20:34:42 INFO]: You are running the latest version
        ```

        </details>
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Paper available from https://papermc.io/downloads.
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: My version of Minecraft is supported by Paper.
          required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful links below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
