name: Performance Problem
description: Report performance related problems or other areas of concern
labels: [ "status: needs triage", "type: performance" ]
body:
  - type: markdown
    attributes:
      value: |
        Before creating an issue regarding server performance, please consider reaching out for support in the
        `#paper-help` channel of [our Discord](https://discord.gg/papermc)!

  - type: input
    attributes:
      label: Profile link
      description: We ask that all profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.
      placeholder: "Example: https://spark.lucko.me/XsN0hxGfsi"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description of issue
      description: If applicable, please describe your issue.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Plugin and Datapack List
      description: |
        All plugins and datapacks running on your server.
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server config files
      description: We need bukkit.yml, spigot.yml, paper-global.yml, paper-world-defaults.yml and server.properties. If you use per-world Paper configs, make sure to include them. You can paste it below or use a paste site like https://paste.gg.
      value: |
        ```
        Paste configs or paste.gg link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Paper version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [20:34:42 INFO]: Checking version, please wait...
        [20:34:42 INFO]: This server is running Paper version 1.21-105-master@7e91a2c (2024-07-20T21:04:31Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
        [20:34:42 INFO]: You are running the latest version
        [20:34:42 INFO]: Previous version: 1.21-103-aa3b356 (MC: 1.21)
        ```

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful links below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. You are running the latest version of Paper from [our downloads page](https://papermc.io/downloads/paper).
        2. You searched for and ensured there isn't already an open issue regarding this.
        3. Your version of Minecraft is supported by Paper.
