package io.papermc.paper.generator;

import com.google.common.collect.ImmutableList;
import io.papermc.paper.generator.references.BlockItemTypeIds;
import java.util.function.Function;
import net.minecraft.references.BlockItemId;
import net.minecraft.references.BlockItemIds;
import net.minecraft.tags.BlockItemTagId;
import net.minecraft.world.level.block.WeatheringCopper;
import net.minecraft.world.level.block.WeatheringCopperCollection;

public class BlockItemTagsProvider extends net.minecraft.data.tags.BlockItemTagsProvider {

    protected BlockItemTagsProvider(final Function<BlockItemTagId, net.minecraft.data.tags.BlockItemTagsProvider.CombinedAppender> tagSupplier) {
        super(tagSupplier);
    }

    public void run() {
        this.tag(BlockItemTags.COBBLESTONE_WALL)
            .add(
                BlockItemTypeIds.MOSSY_COBBLESTONE_WALL,
                BlockItemTypeIds.COBBLESTONE_WALL
            );
        this.tag(BlockItemTags.COBBLESTONE)
            .add(
                BlockItemTypeIds.MOSSY_COBBLESTONE,
                BlockItemTypeIds.COBBLESTONE
            );
        this.tag(BlockItemTags.GLASS)
            .addTag(BlockItemTags.STAINED_GLASS)
            .add(
                BlockItemTypeIds.TINTED_GLASS,
                BlockItemTypeIds.GLASS
            );
        this.tag(BlockItemTags.GLASS_PANE)
            .addTag(BlockItemTags.STAINED_GLASS_PANE)
            .add(BlockItemTypeIds.GLASS_PANE);
        this.tag(BlockItemTags.STAINED_TERRACOTTA)
            .add(
                BlockItemTypeIds.GRAY_TERRACOTTA,
                BlockItemTypeIds.GREEN_TERRACOTTA,
                BlockItemTypeIds.BROWN_TERRACOTTA,
                BlockItemTypeIds.YELLOW_TERRACOTTA,
                BlockItemTypeIds.LIGHT_BLUE_TERRACOTTA,
                BlockItemTypeIds.ORANGE_TERRACOTTA,
                BlockItemTypeIds.RED_TERRACOTTA,
                BlockItemTypeIds.WHITE_TERRACOTTA,
                BlockItemTypeIds.LIME_TERRACOTTA,
                BlockItemTypeIds.LIGHT_GRAY_TERRACOTTA,
                BlockItemTypeIds.CYAN_TERRACOTTA,
                BlockItemTypeIds.MAGENTA_TERRACOTTA,
                BlockItemTypeIds.PINK_TERRACOTTA,
                BlockItemTypeIds.BLACK_TERRACOTTA,
                BlockItemTypeIds.PURPLE_TERRACOTTA,
                BlockItemTypeIds.BLUE_TERRACOTTA
            );
        this.tag(BlockItemTags.TERRACOTTA)
            .addTag(net.minecraft.tags.BlockItemTags.GLAZED_TERRACOTTA)
            .addTag(BlockItemTags.STAINED_TERRACOTTA)
            .add(BlockItemIds.TERRACOTTA);
        this.tag(BlockItemTags.INFESTED_BLOCKS)
            .add(
                BlockItemTypeIds.INFESTED_STONE_BRICKS,
                BlockItemTypeIds.INFESTED_COBBLESTONE,
                BlockItemTypeIds.INFESTED_DEEPSLATE,
                BlockItemTypeIds.INFESTED_STONE,
                BlockItemTypeIds.INFESTED_CHISELED_STONE_BRICKS,
                BlockItemTypeIds.INFESTED_CRACKED_STONE_BRICKS,
                BlockItemTypeIds.INFESTED_MOSSY_STONE_BRICKS
            );
        this.tag(BlockItemTags.MUSHROOM_BLOCKS)
            .add(
                BlockItemTypeIds.BROWN_MUSHROOM_BLOCK,
                BlockItemTypeIds.MUSHROOM_STEM,
                BlockItemTypeIds.RED_MUSHROOM_BLOCK
            );
        this.tag(BlockItemTags.MUSHROOMS)
            .add(
                BlockItemTypeIds.BROWN_MUSHROOM,
                BlockItemTypeIds.RED_MUSHROOM
            );
        this.tag(BlockItemTags.PISTONS)
            .add(
                BlockItemTypeIds.STICKY_PISTON,
                BlockItemTypeIds.PISTON
            );
        this.tag(BlockItemTags.PRISMARINE)
            .add(
                BlockItemTypeIds.PRISMARINE_BRICKS,
                BlockItemTypeIds.PRISMARINE,
                BlockItemTypeIds.DARK_PRISMARINE
            );
        this.tag(BlockItemTags.PRISMARINE_SLABS)
            .add(
                BlockItemTypeIds.PRISMARINE_BRICK_SLAB,
                BlockItemTypeIds.PRISMARINE_SLAB,
                BlockItemTypeIds.DARK_PRISMARINE_SLAB
            );
        this.tag(BlockItemTags.PRISMARINE_STAIRS)
            .add(
                BlockItemTypeIds.DARK_PRISMARINE_STAIRS,
                BlockItemTypeIds.PRISMARINE_BRICK_STAIRS,
                BlockItemTypeIds.PRISMARINE_STAIRS
            );
        this.tag(BlockItemTags.PUMPKIN)
            .add(
                BlockItemTypeIds.CARVED_PUMPKIN,
                BlockItemTypeIds.JACK_O_LANTERN,
                BlockItemTypeIds.PUMPKIN
            );
        this.tag(BlockItemTags.QUARTZ_BLOCKS)
            .add(
                BlockItemTypeIds.CHISELED_QUARTZ_BLOCK,
                BlockItemTypeIds.QUARTZ_BLOCK,
                BlockItemTypeIds.SMOOTH_QUARTZ,
                BlockItemTypeIds.QUARTZ_PILLAR
            );
        this.tag(BlockItemTags.RED_SANDSTONES)
            .add(
                BlockItemTypeIds.SMOOTH_RED_SANDSTONE,
                BlockItemTypeIds.RED_SANDSTONE,
                BlockItemTypeIds.CHISELED_RED_SANDSTONE,
                BlockItemTypeIds.CUT_RED_SANDSTONE
            );
        this.tag(BlockItemTags.SANDSTONES)
            .add(
                BlockItemTypeIds.SMOOTH_SANDSTONE,
                BlockItemTypeIds.CUT_SANDSTONE,
                BlockItemTypeIds.SANDSTONE,
                BlockItemTypeIds.CHISELED_SANDSTONE
            );
        this.tag(BlockItemTags.SPONGE)
            .add(
                BlockItemTypeIds.WET_SPONGE,
                BlockItemTypeIds.SPONGE
            );
        this.tag(BlockItemTags.STAINED_GLASS)
            .add(
                BlockItemTypeIds.GREEN_STAINED_GLASS,
                BlockItemTypeIds.LIGHT_BLUE_STAINED_GLASS,
                BlockItemTypeIds.PURPLE_STAINED_GLASS,
                BlockItemTypeIds.GRAY_STAINED_GLASS,
                BlockItemTypeIds.ORANGE_STAINED_GLASS,
                BlockItemTypeIds.BROWN_STAINED_GLASS,
                BlockItemTypeIds.BLACK_STAINED_GLASS,
                BlockItemTypeIds.WHITE_STAINED_GLASS,
                BlockItemTypeIds.LIGHT_GRAY_STAINED_GLASS,
                BlockItemTypeIds.PINK_STAINED_GLASS,
                BlockItemTypeIds.YELLOW_STAINED_GLASS,
                BlockItemTypeIds.MAGENTA_STAINED_GLASS,
                BlockItemTypeIds.BLUE_STAINED_GLASS,
                BlockItemTypeIds.CYAN_STAINED_GLASS,
                BlockItemTypeIds.LIME_STAINED_GLASS,
                BlockItemTypeIds.RED_STAINED_GLASS
            );
        this.tag(BlockItemTags.STAINED_GLASS_PANE)
            .add(
                BlockItemTypeIds.LIGHT_GRAY_STAINED_GLASS_PANE,
                BlockItemTypeIds.LIGHT_BLUE_STAINED_GLASS_PANE,
                BlockItemTypeIds.LIME_STAINED_GLASS_PANE,
                BlockItemTypeIds.PURPLE_STAINED_GLASS_PANE,
                BlockItemTypeIds.WHITE_STAINED_GLASS_PANE,
                BlockItemTypeIds.PINK_STAINED_GLASS_PANE,
                BlockItemTypeIds.GRAY_STAINED_GLASS_PANE,
                BlockItemTypeIds.BROWN_STAINED_GLASS_PANE,
                BlockItemTypeIds.GREEN_STAINED_GLASS_PANE,
                BlockItemTypeIds.ORANGE_STAINED_GLASS_PANE,
                BlockItemTypeIds.RED_STAINED_GLASS_PANE,
                BlockItemTypeIds.BLUE_STAINED_GLASS_PANE,
                BlockItemTypeIds.BLACK_STAINED_GLASS_PANE,
                BlockItemTypeIds.MAGENTA_STAINED_GLASS_PANE,
                BlockItemTypeIds.CYAN_STAINED_GLASS_PANE,
                BlockItemTypeIds.YELLOW_STAINED_GLASS_PANE
            );
        this.tag(BlockItemTags.PURPUR)
            .add(
                BlockItemTypeIds.PURPUR_PILLAR,
                BlockItemTypeIds.PURPUR_BLOCK,
                BlockItemTypeIds.PURPUR_SLAB,
                BlockItemTypeIds.PURPUR_STAIRS
            );
        this.tag(BlockItemTags.COLORABLE)
            .addTag(net.minecraft.tags.BlockItemTags.WOOL)
            .addTag(net.minecraft.tags.BlockItemTags.WOOL_CARPETS)
            .addTag(net.minecraft.tags.BlockItemTags.SHULKER_BOXES)
            .addTag(net.minecraft.tags.BlockItemTags.BEDS)
            .addTag(net.minecraft.tags.BlockItemTags.CANDLES)
            .addTag(net.minecraft.tags.BlockItemTags.TERRACOTTA)
            .addTag(net.minecraft.tags.BlockItemTags.GLAZED_TERRACOTTA)
            .addTag(net.minecraft.tags.BlockItemTags.CONCRETE)
            .addTag(BlockItemTags.STAINED_GLASS)
            .addTag(BlockItemTags.STAINED_GLASS_PANE);
        this.tag(BlockItemTags.CORAL)
            .add(
                BlockItemTypeIds.BRAIN_CORAL,
                BlockItemTypeIds.DEAD_BRAIN_CORAL,
                BlockItemTypeIds.DEAD_BUBBLE_CORAL,
                BlockItemTypeIds.FIRE_CORAL,
                BlockItemTypeIds.TUBE_CORAL,
                BlockItemTypeIds.HORN_CORAL,
                BlockItemTypeIds.BUBBLE_CORAL,
                BlockItemTypeIds.DEAD_HORN_CORAL,
                BlockItemTypeIds.DEAD_FIRE_CORAL,
                BlockItemTypeIds.DEAD_TUBE_CORAL
            );
        this.tag(BlockItemTags.CORAL_FAN)
            .add(
                BlockItemTypeIds.BRAIN_CORAL_FAN,
                BlockItemTypeIds.TUBE_CORAL_FAN,
                BlockItemTypeIds.DEAD_FIRE_CORAL_FAN,
                BlockItemTypeIds.DEAD_TUBE_CORAL_FAN,
                BlockItemTypeIds.DEAD_BRAIN_CORAL_FAN,
                BlockItemTypeIds.FIRE_CORAL_FAN,
                BlockItemTypeIds.HORN_CORAL_FAN,
                BlockItemTypeIds.DEAD_HORN_CORAL_FAN,
                BlockItemTypeIds.BUBBLE_CORAL_FAN,
                BlockItemTypeIds.DEAD_BUBBLE_CORAL_FAN
            );
        this.tag(BlockItemTags.CORAL_BLOCKS)
            .add(
                BlockItemTypeIds.DEAD_BRAIN_CORAL_BLOCK,
                BlockItemTypeIds.TUBE_CORAL_BLOCK,
                BlockItemTypeIds.DEAD_BUBBLE_CORAL_BLOCK,
                BlockItemTypeIds.BUBBLE_CORAL_BLOCK,
                BlockItemTypeIds.BRAIN_CORAL_BLOCK,
                BlockItemTypeIds.DEAD_HORN_CORAL_BLOCK,
                BlockItemTypeIds.FIRE_CORAL_BLOCK,
                BlockItemTypeIds.DEAD_FIRE_CORAL_BLOCK,
                BlockItemTypeIds.DEAD_TUBE_CORAL_BLOCK,
                BlockItemTypeIds.HORN_CORAL_BLOCK
            );
        this.tag(BlockItemTags.COMMAND_BLOCKS)
            .add(
                BlockItemTypeIds.COMMAND_BLOCK,
                BlockItemTypeIds.REPEATING_COMMAND_BLOCK,
                BlockItemTypeIds.CHAIN_COMMAND_BLOCK
            );
        this.tag(BlockItemTags.FURNACES)
            .add(
                BlockItemTypeIds.FURNACE,
                BlockItemTypeIds.SMOKER,
                BlockItemTypeIds.BLAST_FURNACE
            );
        this.tag(BlockItemTags.ORES)
            .addTag(net.minecraft.tags.BlockItemTags.COAL_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.COPPER_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.IRON_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.GOLD_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.LAPIS_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.REDSTONE_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.DIAMOND_ORES)
            .addTag(net.minecraft.tags.BlockItemTags.EMERALD_ORES)
            .add(
                BlockItemTypeIds.ANCIENT_DEBRIS,
                BlockItemTypeIds.NETHER_QUARTZ_ORE
            );
        this.tag(BlockItemTags.DEEPSLATE_ORES)
            .add(
                BlockItemTypeIds.DEEPSLATE_DIAMOND_ORE,
                BlockItemTypeIds.DEEPSLATE_GOLD_ORE,
                BlockItemTypeIds.DEEPSLATE_COPPER_ORE,
                BlockItemTypeIds.DEEPSLATE_COAL_ORE,
                BlockItemTypeIds.DEEPSLATE_EMERALD_ORE,
                BlockItemTypeIds.DEEPSLATE_REDSTONE_ORE,
                BlockItemTypeIds.DEEPSLATE_IRON_ORE,
                BlockItemTypeIds.DEEPSLATE_LAPIS_ORE
            );
        this.tag(BlockItemTags.RAW_ORE_BLOCKS)
            .add(
                BlockItemTypeIds.RAW_IRON_BLOCK,
                BlockItemTypeIds.RAW_GOLD_BLOCK,
                BlockItemTypeIds.RAW_COPPER_BLOCK
            );
        this.tag(BlockItemTags.OXIDIZED_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_CHEST,
                BlockItemTypeIds.OXIDIZED_LIGHTNING_ROD,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER_SLAB,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER,
                BlockItemTypeIds.OXIDIZED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.OXIDIZED_COPPER_BULB,
                BlockItemTypeIds.OXIDIZED_CHISELED_COPPER,
                BlockItemTypeIds.OXIDIZED_COPPER_GRATE,
                BlockItemTypeIds.OXIDIZED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_DOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_BULB,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.OXIDIZED_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_CHISELED_COPPER,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.OXIDIZED_COPPER_DOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_LIGHTNING_ROD,
                BlockItemTypeIds.OXIDIZED_COPPER_TRAPDOOR
            )
            .addAll(oxidized(BlockItemIds.COPPER_BARS))
            .addAll(oxidized(BlockItemIds.COPPER_LANTERN))
            .addAll(oxidized(BlockItemIds.COPPER_CHAIN));
        this.tag(BlockItemTags.WEATHERED_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.WEATHERED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_WEATHERED_LIGHTNING_ROD,
                BlockItemTypeIds.WEATHERED_CUT_COPPER,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_BULB,
                BlockItemTypeIds.WEATHERED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WEATHERED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.WEATHERED_COPPER,
                BlockItemTypeIds.WEATHERED_LIGHTNING_ROD,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WEATHERED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_WEATHERED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER,
                BlockItemTypeIds.WEATHERED_COPPER_CHEST,
                BlockItemTypeIds.WEATHERED_COPPER_DOOR,
                BlockItemTypeIds.WEATHERED_COPPER_BULB,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER,
                BlockItemTypeIds.WEATHERED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_DOOR,
                BlockItemTypeIds.WEATHERED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_GRATE
            )
            .addAll(weathered(BlockItemIds.COPPER_CHAIN))
            .addAll(weathered(BlockItemIds.COPPER_LANTERN))
            .addAll(weathered(BlockItemIds.COPPER_BARS));
        this.tag(BlockItemTags.EXPOSED_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_BULB,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_DOOR,
                BlockItemTypeIds.EXPOSED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_EXPOSED_LIGHTNING_ROD,
                BlockItemTypeIds.WAXED_EXPOSED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_GRATE,
                BlockItemTypeIds.EXPOSED_CHISELED_COPPER,
                BlockItemTypeIds.EXPOSED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER,
                BlockItemTypeIds.EXPOSED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.EXPOSED_COPPER_BULB,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_TRAPDOOR,
                BlockItemTypeIds.EXPOSED_COPPER_DOOR,
                BlockItemTypeIds.EXPOSED_LIGHTNING_ROD,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.EXPOSED_CUT_COPPER,
                BlockItemTypeIds.EXPOSED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.EXPOSED_COPPER,
                BlockItemTypeIds.EXPOSED_COPPER_TRAPDOOR,
                BlockItemTypeIds.EXPOSED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER_STAIRS
            )
            .addAll(exposed(BlockItemIds.COPPER_CHAIN))
            .addAll(exposed(BlockItemIds.COPPER_LANTERN))
            .addAll(exposed(BlockItemIds.COPPER_BARS));
        this.tag(BlockItemTags.UNAFFECTED_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.CUT_COPPER,
                BlockItemTypeIds.WAXED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.COPPER_BULB,
                BlockItemTypeIds.WAXED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_COPPER_CHEST,
                BlockItemTypeIds.CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_COPPER_BULB,
                BlockItemTypeIds.WAXED_COPPER_BLOCK,
                BlockItemTypeIds.COPPER_DOOR,
                BlockItemTypeIds.CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_COPPER_DOOR,
                BlockItemTypeIds.COPPER_TORCH,
                BlockItemTypeIds.COPPER_GOLEM_STATUE,
                BlockItemTypeIds.CHISELED_COPPER,
                BlockItemTypeIds.COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.COPPER_BLOCK,
                BlockItemTypeIds.COPPER_GRATE,
                BlockItemTypeIds.WAXED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_COPPER_TRAPDOOR,
                BlockItemTypeIds.COPPER_CHEST,
                BlockItemTypeIds.WAXED_CUT_COPPER
            )
            .addAll(unaffected(BlockItemIds.COPPER_BARS))
            .addAll(unaffected(BlockItemIds.COPPER_CHAIN))
            .addAll(unaffected(BlockItemIds.COPPER_LANTERN));
        this.tag(BlockItemTags.WAXED_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_BULB,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_DOOR,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_BULB,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER,
                BlockItemTypeIds.WAXED_COPPER_BLOCK,
                BlockItemTypeIds.WAXED_WEATHERED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.WAXED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_DOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_CUT_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_EXPOSED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER,
                BlockItemTypeIds.WAXED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_COPPER_BULB,
                BlockItemTypeIds.WAXED_COPPER_DOOR,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_CHEST,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_DOOR,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER_BULB,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.WAXED_CHISELED_COPPER,
                BlockItemTypeIds.WAXED_COPPER_GRATE,
                BlockItemTypeIds.WAXED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER_GRATE
            )
            .addAll(asList(BlockItemIds.COPPER_CHAIN.waxed()))
            .addAll(asList(BlockItemIds.COPPER_LANTERN.waxed()))
            .addAll(asList(BlockItemIds.COPPER_BARS.waxed()));
        this.tag(BlockItemTags.UNWAXED_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.EXPOSED_COPPER_GRATE,
                BlockItemTypeIds.WEATHERED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.COPPER_BULB,
                BlockItemTypeIds.WEATHERED_CUT_COPPER_SLAB,
                BlockItemTypeIds.EXPOSED_CUT_COPPER_SLAB,
                BlockItemTypeIds.OXIDIZED_COPPER_BULB,
                BlockItemTypeIds.EXPOSED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.COPPER_DOOR,
                BlockItemTypeIds.WEATHERED_COPPER_CHEST,
                BlockItemTypeIds.CUT_COPPER_SLAB,
                BlockItemTypeIds.EXPOSED_COPPER_BULB,
                BlockItemTypeIds.WEATHERED_COPPER_BULB,
                BlockItemTypeIds.OXIDIZED_COPPER_GRATE,
                BlockItemTypeIds.OXIDIZED_COPPER_GOLEM_STATUE,
                BlockItemTypeIds.COPPER_TORCH,
                BlockItemTypeIds.COPPER_GOLEM_STATUE,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER_SLAB,
                BlockItemTypeIds.EXPOSED_COPPER_DOOR,
                BlockItemTypeIds.WEATHERED_COPPER_GRATE,
                BlockItemTypeIds.COPPER_BLOCK,
                BlockItemTypeIds.EXPOSED_CUT_COPPER,
                BlockItemTypeIds.OXIDIZED_COPPER_DOOR,
                BlockItemTypeIds.EXPOSED_COPPER,
                BlockItemTypeIds.EXPOSED_COPPER_TRAPDOOR,
                BlockItemTypeIds.OXIDIZED_COPPER_TRAPDOOR,
                BlockItemTypeIds.EXPOSED_COPPER_CHEST,
                BlockItemTypeIds.WEATHERED_CHISELED_COPPER,
                BlockItemTypeIds.CUT_COPPER,
                BlockItemTypeIds.OXIDIZED_LIGHTNING_ROD,
                BlockItemTypeIds.WEATHERED_CUT_COPPER,
                BlockItemTypeIds.WEATHERED_COPPER_TRAPDOOR,
                BlockItemTypeIds.WEATHERED_COPPER,
                BlockItemTypeIds.WEATHERED_LIGHTNING_ROD,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER,
                BlockItemTypeIds.OXIDIZED_COPPER_CHEST,
                BlockItemTypeIds.EXPOSED_CHISELED_COPPER,
                BlockItemTypeIds.CUT_COPPER_STAIRS,
                BlockItemTypeIds.OXIDIZED_CHISELED_COPPER,
                BlockItemTypeIds.WEATHERED_COPPER_DOOR,
                BlockItemTypeIds.EXPOSED_LIGHTNING_ROD,
                BlockItemTypeIds.CHISELED_COPPER,
                BlockItemTypeIds.COPPER_TRAPDOOR,
                BlockItemTypeIds.OXIDIZED_COPPER,
                BlockItemTypeIds.COPPER_GRATE,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WEATHERED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.EXPOSED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.COPPER_CHEST
            )
            .addAll(asList(BlockItemIds.COPPER_LANTERN.weathering()))
            .addAll(asList(BlockItemIds.COPPER_CHAIN.weathering()))
            .addAll(asList(BlockItemIds.COPPER_BARS.weathering()));
        this.tag(BlockItemTags.COPPER_BLOCKS)
            .addTag(BlockItemTags.WAXED_COPPER_BLOCKS)
            .addTag(BlockItemTags.UNWAXED_COPPER_BLOCKS);
        this.tag(BlockItemTags.FULL_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.COPPER_BLOCK,
                BlockItemTypeIds.WAXED_WEATHERED_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_COPPER,
                BlockItemTypeIds.WEATHERED_COPPER,
                BlockItemTypeIds.WAXED_COPPER_BLOCK,
                BlockItemTypeIds.OXIDIZED_COPPER,
                BlockItemTypeIds.EXPOSED_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_COPPER
            );
        this.tag(BlockItemTags.CUT_COPPER_BLOCKS)
            .add(
                BlockItemTypeIds.CUT_COPPER,
                BlockItemTypeIds.WAXED_CUT_COPPER,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER,
                BlockItemTypeIds.EXPOSED_CUT_COPPER,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER,
                BlockItemTypeIds.WEATHERED_CUT_COPPER
            );
        this.tag(BlockItemTags.CUT_COPPER_STAIRS)
            .add(
                BlockItemTypeIds.OXIDIZED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WEATHERED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER_STAIRS,
                BlockItemTypeIds.EXPOSED_CUT_COPPER_STAIRS
            );
        this.tag(BlockItemTags.CUT_COPPER_SLABS)
            .add(
                BlockItemTypeIds.WAXED_EXPOSED_CUT_COPPER_SLAB,
                BlockItemTypeIds.CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_WEATHERED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_CUT_COPPER_SLAB,
                BlockItemTypeIds.OXIDIZED_CUT_COPPER_SLAB,
                BlockItemTypeIds.EXPOSED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WAXED_OXIDIZED_CUT_COPPER_SLAB,
                BlockItemTypeIds.WEATHERED_CUT_COPPER_SLAB
            );
    }

    private static ImmutableList<BlockItemId> unaffected(WeatheringCopperCollection<BlockItemId> blocks) {
        return copperVariants(blocks, WeatheringCopper.WeatherState.UNAFFECTED);
    }

    private static ImmutableList<BlockItemId> exposed(WeatheringCopperCollection<BlockItemId> blocks) {
        return copperVariants(blocks, WeatheringCopper.WeatherState.EXPOSED);
    }

    private static ImmutableList<BlockItemId> weathered(WeatheringCopperCollection<BlockItemId> blocks) {
        return copperVariants(blocks, WeatheringCopper.WeatherState.WEATHERED);
    }

    private static ImmutableList<BlockItemId> oxidized(WeatheringCopperCollection<BlockItemId> blocks) {
        return copperVariants(blocks, WeatheringCopper.WeatherState.OXIDIZED);
    }

    private static ImmutableList<BlockItemId> copperVariants(WeatheringCopperCollection<BlockItemId> blocks, WeatheringCopper.WeatherState type) {
        ImmutableList.Builder<BlockItemId> builder = ImmutableList.builderWithExpectedSize(2);
        builder.add(blocks.weathering().pick(type));
        builder.add(blocks.waxed().pick(type));
        return builder.build();
    }

    private static ImmutableList<BlockItemId> asList(WeatheringCopperCollection.ByState<BlockItemId> states) {
        ImmutableList.Builder<BlockItemId> builder = ImmutableList.builderWithExpectedSize(4);
        states.forEach(builder::add);
        return builder.build();
    }
}
