package io.papermc.paper.generator;

import io.papermc.paper.generator.references.ItemTypeIds;
import java.util.concurrent.CompletableFuture;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.BlockItemTagAppender;
import net.minecraft.data.tags.TagsProvider;
import net.minecraft.references.BlockItemId;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

public class ItemTagsProvider extends TagsProvider<Item> {

    public ItemTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, CompletableFuture<TagsProvider.TagLookup<Item>> parentProvider) {
        super(output, Registries.ITEM, lookupProvider, parentProvider);
    }

    @Override
    protected BlockItemTagAppender<Item> tag(final TagKey<Item> tag) {
        return new BlockItemTagAppender<>(super.tag(tag)) {
            @Override
            protected ResourceKey<Item> convertElement(final BlockItemId element) {
                return element.item();
            }
        };
    }

    @Override
    protected void addTags(final HolderLookup.Provider registries) {
        new BlockItemTagsProvider(tagId -> net.minecraft.data.tags.BlockItemTagsProvider.wrapForItems(this.tag(tagId.item()))).run();
        this.tag(ItemTags.BUCKET)
            .addTag(ItemTags.FISH_BUCKET)
            .add(
                ItemTypeIds.POWDER_SNOW_BUCKET,
                ItemTypeIds.TADPOLE_BUCKET,
                ItemTypeIds.AXOLOTL_BUCKET,
                ItemTypeIds.SULFUR_CUBE_BUCKET,
                ItemTypeIds.BUCKET,
                ItemTypeIds.LAVA_BUCKET,
                ItemTypeIds.MILK_BUCKET,
                ItemTypeIds.WATER_BUCKET
            );
        this.tag(ItemTags.BEEHIVES)
            .add(
                ItemTypeIds.BEE_NEST,
                ItemTypeIds.BEEHIVE
            );
        this.tag(ItemTags.FISH_BUCKET)
            .add(
                ItemTypeIds.PUFFERFISH_BUCKET,
                ItemTypeIds.TROPICAL_FISH_BUCKET,
                ItemTypeIds.SALMON_BUCKET,
                ItemTypeIds.COD_BUCKET
            );
        this.tag(ItemTags.ICE)
            .add(
                ItemTypeIds.ICE,
                ItemTypeIds.PACKED_ICE,
                ItemTypeIds.BLUE_ICE
            );
        this.tag(ItemTags.SNOW)
            .add(
                ItemTypeIds.SNOW,
                ItemTypeIds.SNOW_BLOCK
            );
        this.tag(ItemTags.GOLDEN_APPLE)
            .add(
                ItemTypeIds.ENCHANTED_GOLDEN_APPLE,
                ItemTypeIds.GOLDEN_APPLE
            );
        this.tag(ItemTags.HORSE_ARMORS)
            .add(
                ItemTypeIds.GOLDEN_HORSE_ARMOR,
                ItemTypeIds.LEATHER_HORSE_ARMOR,
                ItemTypeIds.COPPER_HORSE_ARMOR,
                ItemTypeIds.DIAMOND_HORSE_ARMOR,
                ItemTypeIds.IRON_HORSE_ARMOR,
                ItemTypeIds.NETHERITE_HORSE_ARMOR
            );
        this.tag(ItemTags.MUSIC_DISCS)
            .add(
                ItemTypeIds.MUSIC_DISC_13,
                ItemTypeIds.MUSIC_DISC_MALL,
                ItemTypeIds.MUSIC_DISC_CAT,
                ItemTypeIds.MUSIC_DISC_MELLOHI,
                ItemTypeIds.MUSIC_DISC_BLOCKS,
                ItemTypeIds.MUSIC_DISC_RELIC,
                ItemTypeIds.MUSIC_DISC_5,
                ItemTypeIds.MUSIC_DISC_CREATOR_MUSIC_BOX,
                ItemTypeIds.MUSIC_DISC_STAL,
                ItemTypeIds.MUSIC_DISC_TEARS,
                ItemTypeIds.MUSIC_DISC_WAIT,
                ItemTypeIds.MUSIC_DISC_CREATOR,
                ItemTypeIds.MUSIC_DISC_WARD,
                ItemTypeIds.MUSIC_DISC_11,
                ItemTypeIds.MUSIC_DISC_LAVA_CHICKEN,
                ItemTypeIds.MUSIC_DISC_PRECIPICE,
                ItemTypeIds.MUSIC_DISC_CHIRP,
                ItemTypeIds.MUSIC_DISC_OTHERSIDE,
                ItemTypeIds.MUSIC_DISC_STRAD,
                ItemTypeIds.MUSIC_DISC_FAR,
                ItemTypeIds.MUSIC_DISC_PIGSTEP,
                ItemTypeIds.MUSIC_DISC_BOUNCE
            );
        this.tag(ItemTags.POTATO)
            .add(
                ItemTypeIds.POTATO,
                ItemTypeIds.BAKED_POTATO,
                ItemTypeIds.POISONOUS_POTATO
            );
        this.tag(ItemTags.COOKED_FISH)
            .add(
                ItemTypeIds.COOKED_COD,
                ItemTypeIds.COOKED_SALMON
            );
        this.tag(ItemTags.RAW_FISH)
            .add(
                ItemTypeIds.SALMON,
                ItemTypeIds.TROPICAL_FISH,
                ItemTypeIds.PUFFERFISH,
                ItemTypeIds.COD
            );
        this.tag(ItemTags.SPAWN_EGGS)
            .add(
                ItemTypeIds.LLAMA_SPAWN_EGG,
                ItemTypeIds.ZOMBIE_HORSE_SPAWN_EGG,
                ItemTypeIds.COW_SPAWN_EGG,
                ItemTypeIds.AXOLOTL_SPAWN_EGG,
                ItemTypeIds.DONKEY_SPAWN_EGG,
                ItemTypeIds.PILLAGER_SPAWN_EGG,
                ItemTypeIds.RAVAGER_SPAWN_EGG,
                ItemTypeIds.BOGGED_SPAWN_EGG,
                ItemTypeIds.SHULKER_SPAWN_EGG,
                ItemTypeIds.BLAZE_SPAWN_EGG,
                ItemTypeIds.PHANTOM_SPAWN_EGG,
                ItemTypeIds.PIG_SPAWN_EGG,
                ItemTypeIds.TADPOLE_SPAWN_EGG,
                ItemTypeIds.SNIFFER_SPAWN_EGG,
                ItemTypeIds.ENDERMITE_SPAWN_EGG,
                ItemTypeIds.FOX_SPAWN_EGG,
                ItemTypeIds.RABBIT_SPAWN_EGG,
                ItemTypeIds.WANDERING_TRADER_SPAWN_EGG,
                ItemTypeIds.VILLAGER_SPAWN_EGG,
                ItemTypeIds.SNOW_GOLEM_SPAWN_EGG,
                ItemTypeIds.ENDER_DRAGON_SPAWN_EGG,
                ItemTypeIds.TRADER_LLAMA_SPAWN_EGG,
                ItemTypeIds.CAT_SPAWN_EGG,
                ItemTypeIds.BAT_SPAWN_EGG,
                ItemTypeIds.VINDICATOR_SPAWN_EGG,
                ItemTypeIds.COD_SPAWN_EGG,
                ItemTypeIds.SILVERFISH_SPAWN_EGG,
                ItemTypeIds.STRIDER_SPAWN_EGG,
                ItemTypeIds.BREEZE_SPAWN_EGG,
                ItemTypeIds.HORSE_SPAWN_EGG,
                ItemTypeIds.WOLF_SPAWN_EGG,
                ItemTypeIds.ZOMBIE_NAUTILUS_SPAWN_EGG,
                ItemTypeIds.FROG_SPAWN_EGG,
                ItemTypeIds.NAUTILUS_SPAWN_EGG,
                ItemTypeIds.WARDEN_SPAWN_EGG,
                ItemTypeIds.PARROT_SPAWN_EGG,
                ItemTypeIds.SKELETON_HORSE_SPAWN_EGG,
                ItemTypeIds.MULE_SPAWN_EGG,
                ItemTypeIds.TURTLE_SPAWN_EGG,
                ItemTypeIds.CAMEL_HUSK_SPAWN_EGG,
                ItemTypeIds.WITHER_SPAWN_EGG,
                ItemTypeIds.SKELETON_SPAWN_EGG,
                ItemTypeIds.IRON_GOLEM_SPAWN_EGG,
                ItemTypeIds.SPIDER_SPAWN_EGG,
                ItemTypeIds.MAGMA_CUBE_SPAWN_EGG,
                ItemTypeIds.PUFFERFISH_SPAWN_EGG,
                ItemTypeIds.ARMADILLO_SPAWN_EGG,
                ItemTypeIds.GLOW_SQUID_SPAWN_EGG,
                ItemTypeIds.ZOMBIE_VILLAGER_SPAWN_EGG,
                ItemTypeIds.GUARDIAN_SPAWN_EGG,
                ItemTypeIds.PIGLIN_SPAWN_EGG,
                ItemTypeIds.DROWNED_SPAWN_EGG,
                ItemTypeIds.EVOKER_SPAWN_EGG,
                ItemTypeIds.PIGLIN_BRUTE_SPAWN_EGG,
                ItemTypeIds.SALMON_SPAWN_EGG,
                ItemTypeIds.HUSK_SPAWN_EGG,
                ItemTypeIds.TROPICAL_FISH_SPAWN_EGG,
                ItemTypeIds.ELDER_GUARDIAN_SPAWN_EGG,
                ItemTypeIds.HAPPY_GHAST_SPAWN_EGG,
                ItemTypeIds.GOAT_SPAWN_EGG,
                ItemTypeIds.POLAR_BEAR_SPAWN_EGG,
                ItemTypeIds.CREEPER_SPAWN_EGG,
                ItemTypeIds.ZOMBIE_SPAWN_EGG,
                ItemTypeIds.DOLPHIN_SPAWN_EGG,
                ItemTypeIds.GHAST_SPAWN_EGG,
                ItemTypeIds.VEX_SPAWN_EGG,
                ItemTypeIds.PARCHED_SPAWN_EGG,
                ItemTypeIds.SHEEP_SPAWN_EGG,
                ItemTypeIds.WITCH_SPAWN_EGG,
                ItemTypeIds.WITHER_SKELETON_SPAWN_EGG,
                ItemTypeIds.ZOGLIN_SPAWN_EGG,
                ItemTypeIds.BEE_SPAWN_EGG,
                ItemTypeIds.CREAKING_SPAWN_EGG,
                ItemTypeIds.CAVE_SPIDER_SPAWN_EGG,
                ItemTypeIds.ENDERMAN_SPAWN_EGG,
                ItemTypeIds.PANDA_SPAWN_EGG,
                ItemTypeIds.SQUID_SPAWN_EGG,
                ItemTypeIds.COPPER_GOLEM_SPAWN_EGG,
                ItemTypeIds.HOGLIN_SPAWN_EGG,
                ItemTypeIds.CHICKEN_SPAWN_EGG,
                ItemTypeIds.MOOSHROOM_SPAWN_EGG,
                ItemTypeIds.OCELOT_SPAWN_EGG,
                ItemTypeIds.SLIME_SPAWN_EGG,
                ItemTypeIds.STRAY_SPAWN_EGG,
                ItemTypeIds.ALLAY_SPAWN_EGG,
                ItemTypeIds.CAMEL_SPAWN_EGG,
                ItemTypeIds.SULFUR_CUBE_SPAWN_EGG,
                ItemTypeIds.ZOMBIFIED_PIGLIN_SPAWN_EGG
            );
        this.tag(ItemTags.TORCHES)
            .add(
                ItemTypeIds.REDSTONE_TORCH,
                ItemTypeIds.SOUL_TORCH,
                ItemTypeIds.COPPER_TORCH,
                ItemTypeIds.TORCH
            );
        this.tag(ItemTags.CAMPFIRES)
            .add(
                ItemTypeIds.CAMPFIRE,
                ItemTypeIds.SOUL_CAMPFIRE
            );
        this.tag(ItemTags.ARMOR)
            .addTag(net.minecraft.tags.ItemTags.HEAD_ARMOR)
            .addTag(net.minecraft.tags.ItemTags.CHEST_ARMOR)
            .addTag(net.minecraft.tags.ItemTags.LEG_ARMOR)
            .addTag(net.minecraft.tags.ItemTags.FOOT_ARMOR);
        this.tag(ItemTags.BOWS)
            .add(
                ItemTypeIds.BOW,
                ItemTypeIds.CROSSBOW
            );
        this.tag(ItemTags.THROWABLE_PROJECTILES)
            .addTag(net.minecraft.tags.ItemTags.EGGS)
            .add(
                ItemTypeIds.SNOWBALL,
                ItemTypeIds.WIND_CHARGE,
                ItemTypeIds.TRIDENT,
                ItemTypeIds.FIREWORK_ROCKET,
                ItemTypeIds.LINGERING_POTION,
                ItemTypeIds.ENDER_PEARL,
                ItemTypeIds.SPLASH_POTION,
                ItemTypeIds.EXPERIENCE_BOTTLE
            );
        this.tag(ItemTags.COLORABLE)
            .addTag(net.minecraft.tags.ItemTags.CONCRETE_POWDERS);
        this.tag(ItemTags.NYLIUM)
            .add(
                ItemTypeIds.CRIMSON_NYLIUM,
                ItemTypeIds.WARPED_NYLIUM
            );
        this.tag(ItemTags.RAW_ORES)
            .add(
                ItemTypeIds.RAW_GOLD,
                ItemTypeIds.RAW_IRON,
                ItemTypeIds.RAW_COPPER
            );
        this.tag(ItemTags.PRESSURE_PLATES)
            .addTag(net.minecraft.tags.ItemTags.WOODEN_PRESSURE_PLATES)
            .addTag(ItemTags.STONE_PRESSURE_PLATES)
            .add(
                ItemTypeIds.LIGHT_WEIGHTED_PRESSURE_PLATE,
                ItemTypeIds.HEAVY_WEIGHTED_PRESSURE_PLATE
            );
        this.tag(ItemTags.STONE_PRESSURE_PLATES)
            .add(
                ItemTypeIds.STONE_PRESSURE_PLATE,
                ItemTypeIds.POLISHED_BLACKSTONE_PRESSURE_PLATE
            );
        this.tag(ItemTags.WOODEN_TOOLS)
            .add(
                ItemTypeIds.WOODEN_HOE,
                ItemTypeIds.WOODEN_AXE,
                ItemTypeIds.WOODEN_SHOVEL,
                ItemTypeIds.WOODEN_SWORD,
                ItemTypeIds.WOODEN_PICKAXE,
                ItemTypeIds.WOODEN_SPEAR
            );
        this.tag(ItemTags.STONE_TOOLS)
            .add(
                ItemTypeIds.STONE_PICKAXE,
                ItemTypeIds.STONE_SPEAR,
                ItemTypeIds.STONE_AXE,
                ItemTypeIds.STONE_HOE,
                ItemTypeIds.STONE_SHOVEL,
                ItemTypeIds.STONE_SWORD
            );
        this.tag(ItemTags.COPPER_TOOLS)
            .add(
                ItemTypeIds.COPPER_SHOVEL,
                ItemTypeIds.COPPER_SWORD,
                ItemTypeIds.COPPER_SPEAR,
                ItemTypeIds.COPPER_HOE,
                ItemTypeIds.COPPER_AXE,
                ItemTypeIds.COPPER_PICKAXE
            );
        this.tag(ItemTags.IRON_TOOLS)
            .add(
                ItemTypeIds.IRON_AXE,
                ItemTypeIds.IRON_SPEAR,
                ItemTypeIds.IRON_HOE,
                ItemTypeIds.IRON_PICKAXE,
                ItemTypeIds.IRON_SWORD,
                ItemTypeIds.IRON_SHOVEL
            );
        this.tag(ItemTags.GOLDEN_TOOLS)
            .add(
                ItemTypeIds.GOLDEN_AXE,
                ItemTypeIds.GOLDEN_SHOVEL,
                ItemTypeIds.GOLDEN_SWORD,
                ItemTypeIds.GOLDEN_PICKAXE,
                ItemTypeIds.GOLDEN_SPEAR,
                ItemTypeIds.GOLDEN_HOE
            );
        this.tag(ItemTags.DIAMOND_TOOLS)
            .add(
                ItemTypeIds.DIAMOND_HOE,
                ItemTypeIds.DIAMOND_SWORD,
                ItemTypeIds.DIAMOND_AXE,
                ItemTypeIds.DIAMOND_PICKAXE,
                ItemTypeIds.DIAMOND_SHOVEL,
                ItemTypeIds.DIAMOND_SPEAR
            );
        this.tag(ItemTags.NETHERITE_TOOLS)
            .add(
                ItemTypeIds.NETHERITE_AXE,
                ItemTypeIds.NETHERITE_SWORD,
                ItemTypeIds.NETHERITE_HOE,
                ItemTypeIds.NETHERITE_SHOVEL,
                ItemTypeIds.NETHERITE_PICKAXE,
                ItemTypeIds.NETHERITE_SPEAR
            );
        this.tag(BlockItemTags.UNWAXED_COPPER_BLOCKS.item())
            .add(ItemTypeIds.COPPER_TORCH);
        this.tag(BlockItemTags.UNAFFECTED_COPPER_BLOCKS.item())
            .add(ItemTypeIds.COPPER_TORCH);
    }
}
