package org.bukkit.loot;

import java.util.Collection;
import java.util.Random;
import net.kyori.adventure.key.Key;
import org.bukkit.Keyed;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Loot tables are technical files that represent what items should be in
 * naturally generated containers, what items should be dropped when killing a
 * mob, or what items can be fished.
 * <br>
 * See the <a href="https://minecraft.wiki/w/Loot_table">
 * Minecraft Wiki</a> for more information.
 */
public interface LootTable extends Keyed {

    /**
     * @deprecated use {@link org.bukkit.Registry#getKey(Keyed)}, {@link io.papermc.paper.registry.RegistryAccess#getRegistry(io.papermc.paper.registry.RegistryKey)},
     * and {@link io.papermc.paper.registry.RegistryKey#LOOT_TABLE}. Loot tables can exist without a key.
     */
    @Deprecated(since = "1.21.11", forRemoval = true)
    @Override
    NamespacedKey getKey();

    /**
     * @deprecated use {@link org.bukkit.Registry#getKey(Keyed)}, {@link io.papermc.paper.registry.RegistryAccess#getRegistry(io.papermc.paper.registry.RegistryKey)},
     * and {@link io.papermc.paper.registry.RegistryKey#LOOT_TABLE}. Loot tables can exist without a key.
     */
    @Deprecated(since = "1.21.11", forRemoval = true)
    @Override
    default Key key() {
        return Keyed.super.key();
    }

    /**
     * Returns a mutable list of loot generated by this LootTable.
     *
     * @param random the random instance to use to generate loot
     * @param context context within to populate loot
     * @return a list of ItemStacks
     */
    @NotNull
    Collection<ItemStack> populateLoot(@Nullable Random random, @NotNull LootContext context);

    /**
     * Attempt to fill an inventory with this LootTable's loot.
     *
     * @param inventory the inventory to fill
     * @param random the random instance to use to generate loot
     * @param context context within to populate loot
     */
    void fillInventory(@NotNull Inventory inventory, @Nullable Random random, @NotNull LootContext context);
}
