# Here lie dragons!
#
# This action either builds the server or
# builds a paperclip jar to be updated in the body
# of the PR relating to this action.

name: Build Paper

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches-ignore:
      - main

jobs:
  build:
    env:
      ORG_GRADLE_PROJECT_paperBuildCacheEnabled: true
      ORG_GRADLE_PROJECT_paperBuildCacheUsername: ${{ secrets.PAPER_BUILD_CACHE_USERNAME }}
      ORG_GRADLE_PROJECT_paperBuildCachePassword: ${{ secrets.PAPER_BUILD_CACHE_PASSWORD }}
      ORG_GRADLE_PROJECT_paperBuildCachePush: true

    # The goal of the build workflow is split into multiple requirements.
    # 1. Run on pushes to same repo.
    # 2. Run on PR open/reopen/syncs from repos that are not the same (PRs from the same repo are covered by 1)
    # 3. Run on labeled PRs that have the publish-pr flag.
    if: >
      (
        (github.event_name == 'push')
        || (github.event_name == 'pull_request' && github.repository != github.event.pull_request.head.repo.full_name && contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action))
        || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'publish-pr')
      )

    runs-on: namespace-profile-linux-default
    steps:
      - name: "git / checkout (push)"
        uses: namespacelabs/nscloud-checkout-action@66f2dc6f6c42a8ac6c4e53473c4840006822831e # v9.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: "git / checkout (pull request)"
        if: ${{ github.event_name == 'pull_request' }}
        uses: namespacelabs/nscloud-checkout-action@66f2dc6f6c42a8ac6c4e53473c4840006822831e # v9.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # todo: cache-read-only: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/dev/') }}
      - uses: papermc/ci/setup-gradle@main

      - name: Configure Build
        uses: actions/github-script@v9
        id: determine
        with:
          script: |
            const { owner, repo } = context.repo;
            const result = {
              action: "build"
            };

            if (context.eventName === "push" && process.env.GITHUB_REF_TYPE === "branch") {
              const { data: pulls } = await github.rest.pulls.list({
                owner,
                repo,
                head: `${owner}:${process.env.GITHUB_REF_NAME}`,
                state: "open"
              });
              const pull = pulls.find((pr) => !!pr.labels.find((l) => l.name === "publish-pr"));
              if (pull) {
                result["pr"] = pull.number;
                result["action"] = "paperclip";
                core.notice(`This is a push action but to a branch with an open PR with the build paperclip label (${JSON.stringify(result)})`);
                return result;
              }
            } else if (context.eventName === "pull_request" && context.payload.pull_request.labels.find((l) => l.name === "publish-pr")) {
              result["pr"] = context.payload.pull_request.number;
              result["action"] = "paperclip";
              core.notice(`This is a pull request action with a build paperclip label (${JSON.stringify(result)})`);
              return result;
            }
            core.notice("This will not build a paperclip jar");
            return result;

      - uses: papermc/ci/build-paper@main

      - uses: papermc/ci/upload-test-results@main

      - name: Publish Checkstyle Report
        if: ${{ failure() || success() }}
        uses: Juuxel/publish-checkstyle-report@16e2829b4f75e652523ab9baf32276bd3de62202 # v3.0.0
        with:
          reports: |
            */build/reports/checkstyle/*.xml

      - name: "gradle / package"
        if: fromJSON(steps.determine.outputs.result).action == 'paperclip'
        run: ./gradlew createPaperclipJar --stacktrace

      - name: "upload / paperclip"
        if: fromJSON(steps.determine.outputs.result).action == 'paperclip'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: paper-${{ fromJSON(steps.determine.outputs.result).pr }}
          path: paper-server/build/libs/paper-paperclip-*.jar

      - name: Publish Artifacts
        if: fromJSON(steps.determine.outputs.result).action == 'paperclip'
        uses: PaperMC/action-pr-publishing/upload@paper
        with:
          # TODO fallback for failing javadoc
          publishing-task: ":paper-api:publishAllPublicationsTo_githubPackages_PRsRepository publishDevBundlePublicationTo_githubPackages_PRsRepository -PpublishDevBundle"

  event_file:
    name: "Event File"
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: namespace-profile-linux-small
    permissions:
      actions: write
    steps:
      - name: "upload / event data"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: event-data
          path: ${{ github.event_path }}
