name: PR Review Signal

on:
  pull_request_review:
    types:
      - submitted

permissions: {}

jobs:
  signal:
    runs-on: namespace-profile-linux-small
    steps:
      - run: echo "A PR review was submitted"
