name: Release 26.3

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  cancel-in-progress: false
  group: release-26.3

jobs:
  release:
    runs-on: namespace-profile-linux-default
    timeout-minutes: 30
    #env:
    #  BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: "environment"
        run: |
          echo "BUILD_NUMBER=$((129 + GITHUB_RUN_NUMBER))" >> "$GITHUB_ENV"
          echo "BUILD_STARTED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"

      - name: "git / checkout"
        uses: namespacelabs/nscloud-checkout-action@66f2dc6f6c42a8ac6c4e53473c4840006822831e # v9.0.1
        with:
          fetch-depth: 0

      - uses: papermc/ci/setup-gradle@main

      - uses: papermc/ci/build-paper@main

      - if: ${{ !cancelled() }}
        uses: papermc/ci/upload-event-data@main
        with:
          path: ${{ github.event_path }}

      - if: ${{ !cancelled() }}
        uses: papermc/ci/upload-test-results@main

      - uses: papermc/ci/publish-fill@main
        with:
          fill_api_url: ${{ secrets.FILL_API_URL }}
          fill_api_key: ${{ secrets.FILL_API_KEY }}

      - uses: papermc/ci/publish-maven@main
        with:
          maven_username: ${{ secrets.ARTIFACTORY_USERNAME }}
          maven_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          maven_tasks: -PpublishDevBundle :paper-api:publish publishDevBundlePublicationToPaperReleasesRepository
